## 플레이북 설정 파일

# 1. 모든 VM에 공개키 복사
- name: VM에 SSH 공개키 등록 (무비번 접속용)
  hosts: all
  gather_facts: false
  vars:
    ssh_pub_key: "{{ lookup('file', '/home/vagrant/.ssh/id_ed25519.pub') }}"
  tasks:
    - name: .ssh 디렉토리 생성
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0700'

    - name: 공개키를 authorized_keys에 추가
      authorized_key:
        user: vagrant
        key: "{{ ssh_pub_key }}"

# 2. 모든 VM의 스왑 메모리 비활성화
- name: Disable swap on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Disable swap immediately
      command: swapoff -a

    - name: Comment out swap line in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*swap)'
        replace: '# \1'

# 3. 마스터 설치
- name: Install K3s on master node with Flannel CNI
  hosts: master
  become: yes
  tasks:
    - name: Install K3s with Flannel backend
      shell: |
        curl -sfL https://get.k3s.io | sh -s - \
          --write-kubeconfig-mode 644 \
          --tls-san {{ hostvars[inventory_hostname]['ansible_host'] }} \
          --node-ip {{ hostvars[inventory_hostname]['ansible_host'] }}
      args:
        creates: /etc/systemd/system/k3s.service

# 4. 모든 Worker 노드에 K3s 에이전트 설치
- name: Install K3s on workers
  hosts: workers
  become: yes
  vars:
    k3s_token: "{{ hostvars['vm1']['k3s_token'] }}"
    master_ip: "{{ hostvars['vm1']['ansible_host'] }}"
  tasks:
    - name: Wait for master node token to be available
      delegate_to: vm1
      become: yes
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token_output

    - name: Set K3s token fact
      set_fact:
        k3s_token: "{{ token_output['content'] | b64decode | trim }}"

    - name: Download and install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service